AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Security Group allowing only HTTPS (443)'

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow traffic only on port 443 (HTTPS)"
      VpcId: vpc-0f56c1645f68cb682
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443             # HTTPS
          ToPort: 443
          CidrIp: 0.0.0.0/0         # Open to all IPs
      Tags:
        - Key: "https"
          Value: "443"

Outputs:
  SecurityGroupId:
    Description: "The ID of the Security Group"
    Value: !Ref MySecurityGroup
